---
- name: install dependencies
  hosts: nxts
  gather_facts: no
  tasks:
  - name: install jre
    apt: pkg=openjdk-7-jre state=latest
    sudo: yes
  - name: install unzip
    apt: pkg=unzip state=latest
    sudo: yes

- name: update nxt
  hosts: nxts
  gather_facts: no
  vars:
    nxt_local_folder: ~/ansible/nxt
    nxt_remote_folder: ~/nxt-kit
  tasks:
  - name: check remote folders
    file: path={{ item }} state=directory owner={{ ansible_ssh_user }} mode=0744
    with_items:
      - "{{ nxt_remote_folder }}"
      - "{{ nxt_remote_folder }}/distrib"
      - "{{ nxt_remote_folder }}/sbin"
  - name: calculate local md5
    local_action: shell /usr/bin/md5sum {{ nxt_local_folder }}/distrib/nxt.zip | awk '{print $1;}'
    register: localmd5
  - name: calculate remote md5
    shell: /usr/bin/md5sum {{ nxt_remote_folder }}/distrib/nxt.zip | awk '{print $1;}'
    register: remotemd5
  - name: copy lastest distrib
    when: localmd5.stdout != remotemd5.stdout
    copy: src={{ nxt_local_folder }}/distrib/nxt.zip dest={{ nxt_remote_folder }}/distrib
    notify:
    - uncron restart script
    - uncron check script
    - kill nxt
    - unpack new version
    - setup web config
    - run nxt
    
  handlers:
    - name: uncron restart script
      cron: name="nxt memory leak workaround" state=absent
    - name: uncron check script
      cron: name="is nxt running" state=absent
    - name: kill nxt
      shell: pkill java || /bin/true
    - name: unpack new version
      shell: cd {{ nxt_remote_folder }} && rm -rf nxt && unzip distrib/nxt.zip 
    - name: setup web config
      template: src={{ nxt_local_folder }}/templates/web.j2 dest={{ nxt_remote_folder }}/nxt/webapps/root/WEB-INF/web.xml
    - name: run nxt
      script: "{{ nxt_local_folder }}/scripts-src/check.sh"

- name: ensure check and restart scripts @ cron
  hosts: nxts
  gather_facts: no
  vars:
    nxt_local_folder: ~/ansible/nxt
    nxt_remote_folder: ~/nxt-kit
  tasks:
  - name: copy check script
    copy: src={{ nxt_local_folder }}/scripts-src/check.sh dest={{ nxt_remote_folder }}/sbin/check.nxt.sh mode=0744
  - name: copy restart script
    copy: src={{ nxt_local_folder }}/scripts-src/restart.sh dest={{ nxt_remote_folder }}/sbin/restart.nxt.sh mode=0744
  - name: cron check script
    cron: name="is nxt running" job="{{ nxt_remote_folder }}/sbin/check.nxt.sh"
  - name: cron restart script
    cron: name="nxt memory leak workaround" special_time=hourly  job="{{ nxt_remote_folder }}/sbin/restart.nxt.sh"
