---
- name: flush cache
  hosts: nxts
  gather_facts: no
  vars:
    nxt_local_folder: ~/ansible/nxt
    nxt_remote_folder: ~/nxt-kit
  tasks:
  - name: calculate local md5
    local_action: shell /usr/bin/md5sum {{ nxt_local_folder }}/distrib/{{ item }} | awk '{print $1;}'
    with_items:
      - "chain-original.tar.gz"
    changed_when: false
    register: localmd5
  - name: calculate remote md5
    shell: /usr/bin/md5sum {{ nxt_remote_folder }}/distrib/{{ item }} | awk '{print $1;}'
    with_items:
      - "chain-original.tar.gz"
    changed_when: false
    register: remotemd5
  - name: copy original chain
    copy: src={{ nxt_local_folder }}/distrib/chain-original.tar.gz dest={{ nxt_remote_folder }}/distrib
    when: localmd5.results[0].stdout != remotemd5.results[0].stdout
  - name: uncron check script
    cron: name="is nxt running" state=absent
  - name: kill check script
    shell: pkill -f 'check.nxt.sh'
    ignore_errors: yes
  - name: remove cached chain
    file: path="{{ nxt_remote_folder }}/distrib/chain.tar.gz" state=absent
  - name: kill nxt
    shell: pkill -f 'java \-jar start.jar'
    ignore_errors: yes
  - name: cron check script
    cron: name="is nxt running" job="{{ nxt_remote_folder }}/sbin/check.nxt.sh"
